### ISSUE TITLE
Description column

### ISSUE THREAD

**Issue by omergulen** [wwdc/2019#12]
I think adding a description column would be great, once I looked up for the last years projects I always desired to know what is it about and sometimes I went to code, sometimes I went to Youtube but I think 1-2 sentence description would be great.

**Comment by lucashoeft** [comment]
Check #2

**Comment by omergulen** [comment]
I definitely didn't see it xd I can try to help with that!

**Comment by Schemetrical** [comment]
Closed as duplicate of #2
